
GET 'http://localhost:3000/'


#############

POST  'http://localhost:3000/create/'
Content-Type: application/json

{
    "ticker":"A",
    "date": 2020/01/01,
    "revenue":1483000000,
    "gp":788000000,
    "fcf":350000000,
    "capex":27000000
}


#########

DELETE 'http://localhost:3000/delete/1'
